#!/bin/bash

#=== Global Vars ===
DEBUGMODE=1 #0:OFF 1:ON

#=== Main Logic ===
function main
{
  #------------
  #Time Stamp
  local srtdatetime=`date +%Y%m%d_%H%M%S_%3N`
  ilog "[mgit-clone] start : ${srtdatetime}"

  #------------
  #create list file
  local _ReposUrlsFileName='reposlist_url'
  local _ReposUrlsFile="./${_ReposUrlsFileName}.txt"
  dlog "_ReposUrlsFileName    = ${_ReposUrlsFileName}"
  dlog "_ReposUrlsFile        = ${_ReposUrlsFile}"
  if [ ! -e ${_ReposUrlsFile} ]; then
    elog "${_ReposUrlsFile} not found."
    exit 1
  fi 

  #edit list file
  #vi ${_ReposUrlsFile}

  #read list file
  local _ReposList=`cat ${_ReposUrlsFile}`
  dlog "_ReposList = ${_ReposList}"
  for _cloneurl in ${_ReposList}
  do
    dlog "${_cloneurl}"
    git clone ${_cloneurl}
  done
  
  #------------
  #End Time Stamp
  local enddatetime=`date +%Y%m%d_%H%M%S_%3N`
  ilog "[mgit-clone] finished : ${enddatetime}"
  echo -e

}


#=== Log Functions ===
#function recho { echo -e '\e[31m$*\e[m'; } #Linux
function recho { echo -e $'\e[31m'$*$'\e[m'; } #For Mac
function gecho { echo -e $'\e[32m'$*$'\e[m'; } #For Mac
function yecho { echo -e $'\e[33m'$*$'\e[m'; } #For Mac
function becho { echo -e $'\e[34m'$*$'\e[m'; } #For Mac
function mecho { echo -e $'\e[35m'$*$'\e[m'; } #For Mac
function cecho { echo -e $'\e[36m'$*$'\e[m'; } #For Mac
function log
{
  if [ $DEBUGMODE -ne 0 ]; then
    echo -e $'\e[m[Log] '$*;
  fi
}
function elog
{
  if [ $DEBUGMODE -ne 0 ]; then
    echo -e $'\e[43;31m[Error] '$*$'\e[m';
    echo -e
  fi
}
function ilog
{
  if [ $DEBUGMODE -ne 0 ]; then
    echo -e $'\e[32m[Info] '$*$'\e[m';
  fi
}
function dlog
{
  if [ $DEBUGMODE -ne 0 ]; then
    echo -e $'\e[33m[Debug] '$*$'\e[m';
  fi
}

#=== Entry Point ===
main $*

#=== Exit Shell ===
exit 0

